### ISSUE TITLE
Failure in installing MinkowskiEngine

### ISSUE THREAD

**Issue by toannguyen1904** [atcelen/IDesign#2]
Hi! This is such an amazing project.
I face a problem in installing MinkowskiEngine, like many others [mentioned](https://github.com/NVIDIA/MinkowskiEngine/issues/551) in their GitHub repo. I checked your code and did not find out the package being used anywhere. Do I need to install the engine? If I have to, can you suggest me some solutions?

Thanks in advance!

**Comment by atcelen** [comment]
The MinkowskiEngine is used inside the "retrieve.py" script, which uses this library as the backbone of the OpenShape, which is used to retrieve 3D assets from Objaverse. 

Installing MinkowskiEngine has been somewhat challenging. From my debugging experience, it appears that MinkowskiEngine does not currently support Windows machines. If you're using Windows, I recommend using WSL, which worked for me. Additionally, I encountered problems when trying to install it with CUDA 12.X, but switching to CUDA 11.7 resolved these issues. Please let me know about your setup so I can assist you further.

**Comment by toannguyen1904** [comment]
Hi, thanks for the quick response. I followed the same packages installation steps in your README. My current setting is Ubuntu 20.04.4 and CUDA 11.8. The error persists regardless CUDA version of 12.3 or 11.8, I tried both. Some of the error log can be observed below
```
File "/cm/shared/toannt28/miniconda3/envs/idesign/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/cm/shared/toannt28/miniconda3/envs/idesign/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/cm/shared/toannt28/miniconda3/envs/idesign/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for MinkowskiEngine
  Running setup.py clean for MinkowskiEngine
Failed to build MinkowskiEngine
ERROR: Could not build wheels for MinkowskiEngine, which is required to install pyproject.toml-based projects
```

**Comment by toannguyen1904** [comment]
Hi @atcelen, I decided not to install the MinkowskiEngine and everything worked just fine. Seems like the model you chose does not use the backbone requiring MinkowskiEngine, as mentioned [here](https://github.com/Colin97/OpenShape_code/issues/10#issuecomment-1685204086). Do you have any idea?

**Comment by atcelen** [comment]
Hello, I have not had the chance to look in detail to your issue. I will try to reinstall the MinkowskiEngine on my machine from scratch on a new environment. I will report what the issue might have been. However, as you said, our pipeline doesn't depend on the MinkowskiEngine.

**Comment by maria-ny** [comment]
> The MinkowskiEngine is used inside the "retrieve.py" script, which uses this library as the backbone of the OpenShape, which is used to retrieve 3D assets from Objaverse.
> 
> Installing MinkowskiEngine has been somewhat challenging. From my debugging experience, it appears that MinkowskiEngine does not currently support Windows machines. If you're using Windows, I recommend using WSL, which worked for me. Additionally, I encountered problems when trying to install it with CUDA 12.X, but switching to CUDA 11.7 resolved these issues. Please let me know about your setup so I can assist you further.



I tried switching to CUDA 11.7. This is the set of commands I tried to make the MinkowskiEngine work, but it fails:

```
sudo apt-get install g++
conda create -n idesign python=3.9
conda activate idesign
conda install cuda -c nvidia/label/cuda-11.7.0
pip install -r requirements.txt
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 -c pytorch
conda install openblas
conda install conda-forge::python-devtools
python setup.py install --cpu_only
conda install ninja
git clone https://github.com/NVIDIA/MinkowskiEngine.git
cd MinkowskiEngine/
python setup.py install --cpu_only --blas_include_dirs=home/username/miniconda3/include --blas=openblas
```

The errors right now are mostly missing headers there:
```
MinkowskiEngine/src/quantization.cpp:28:10: fatal error: pybind11/numpy.h: No such file or directory
   28 | #include <pybind11/numpy.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

Any chance you could include a docker file with the working set-up? Sometimes it is more reliable than conda

**Comment by atcelen** [comment]
Hello,

I believe providing a Dockerfile should be the easiest to tackle the problem of installing the Minkowski Engine. I have just updated the repository with a docker file.

Some Notes:
- Install NVIDIA Container Toolkit for GPU visibility within the container
- Use the `--gpus all` option when running the container
